// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { McpOptions } from './options';

export type SdkMethod = {
  clientCallName: string;
  fullyQualifiedName: string;
  httpMethod?: 'get' | 'post' | 'put' | 'patch' | 'delete' | 'query';
  httpPath?: string;
};

export const sdkMethods: SdkMethod[] = [
  {
    clientCallName: 'client.auth.apiKeys.retrieve',
    fullyQualifiedName: 'auth.apiKeys.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/auth/api-keys/{id}',
  },
  {
    clientCallName: 'client.auth.apiKeys.list',
    fullyQualifiedName: 'auth.apiKeys.list',
    httpMethod: 'get',
    httpPath: '/v1/auth/api-keys',
  },
  {
    clientCallName: 'client.auth.apiKeys.create',
    fullyQualifiedName: 'auth.apiKeys.create',
    httpMethod: 'post',
    httpPath: '/v1/auth/api-keys',
  },
  {
    clientCallName: 'client.auth.apiKeys.delete',
    fullyQualifiedName: 'auth.apiKeys.delete',
    httpMethod: 'delete',
    httpPath: '/v1/auth/api-keys/{id}',
  },
  {
    clientCallName: 'client.auth.apiKeys.actions.rotate',
    fullyQualifiedName: 'auth.apiKeys.actions.rotate',
    httpMethod: 'post',
    httpPath: '/v1/auth/api-keys/{id}/actions/rotate',
  },
  {
    clientCallName: 'client.core.retrieveSearch',
    fullyQualifiedName: 'core.retrieveSearch',
    httpMethod: 'get',
    httpPath: '/v1/core/search',
  },
  {
    clientCallName: 'client.core.sandboxes.list',
    fullyQualifiedName: 'core.sandboxes.list',
    httpMethod: 'get',
    httpPath: '/v1/core/sandboxes',
  },
  {
    clientCallName: 'client.core.sandboxes.retrieve',
    fullyQualifiedName: 'core.sandboxes.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/core/sandboxes/{id}',
  },
  {
    clientCallName: 'client.core.sandboxes.create',
    fullyQualifiedName: 'core.sandboxes.create',
    httpMethod: 'post',
    httpPath: '/v1/core/sandboxes',
  },
  {
    clientCallName: 'client.core.sandboxes.delete',
    fullyQualifiedName: 'core.sandboxes.delete',
    httpMethod: 'delete',
    httpPath: '/v1/core/sandboxes/{id}',
  },
  {
    clientCallName: 'client.core.requestLogs.list',
    fullyQualifiedName: 'core.requestLogs.list',
    httpMethod: 'get',
    httpPath: '/v1/core/request-logs',
  },
  {
    clientCallName: 'client.core.requestLogs.retrieve',
    fullyQualifiedName: 'core.requestLogs.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/core/request-logs/{id}',
  },
  {
    clientCallName: 'client.core.auditEvents.list',
    fullyQualifiedName: 'core.auditEvents.list',
    httpMethod: 'get',
    httpPath: '/v1/core/audit-events',
  },
  {
    clientCallName: 'client.core.auditEvents.retrieve',
    fullyQualifiedName: 'core.auditEvents.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/core/audit-events/{id}',
  },
  {
    clientCallName: 'client.core.auditEvents.retrieveResourceTypes',
    fullyQualifiedName: 'core.auditEvents.retrieveResourceTypes',
    httpMethod: 'get',
    httpPath: '/v1/core/audit-events/resource-types',
  },
  {
    clientCallName: 'client.core.addresses.retrieveSuggestions',
    fullyQualifiedName: 'core.addresses.retrieveSuggestions',
    httpMethod: 'get',
    httpPath: '/v1/core/addresses/suggestions',
  },
  {
    clientCallName: 'client.core.addresses.actions.validate',
    fullyQualifiedName: 'core.addresses.actions.validate',
    httpMethod: 'put',
    httpPath: '/v1/core/addresses/actions/validate',
  },
  {
    clientCallName: 'client.core.emailLogs.list',
    fullyQualifiedName: 'core.emailLogs.list',
    httpMethod: 'get',
    httpPath: '/v1/core/email-logs',
  },
  {
    clientCallName: 'client.core.emailLogs.retrieve',
    fullyQualifiedName: 'core.emailLogs.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/core/email-logs/{id}',
  },
  {
    clientCallName: 'client.core.jobs.retrieve',
    fullyQualifiedName: 'core.jobs.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/core/jobs/{id}',
  },
  {
    clientCallName: 'client.core.jobs.cancel',
    fullyQualifiedName: 'core.jobs.cancel',
    httpMethod: 'post',
    httpPath: '/v1/core/jobs/{id}/cancel',
  },
  {
    clientCallName: 'client.core.analytics.updateOee',
    fullyQualifiedName: 'core.analytics.updateOee',
    httpMethod: 'put',
    httpPath: '/v1/core/analytics/oee',
  },
  {
    clientCallName: 'client.core.analytics.updateOeeTrend',
    fullyQualifiedName: 'core.analytics.updateOeeTrend',
    httpMethod: 'put',
    httpPath: '/v1/core/analytics/oee-trend',
  },
  {
    clientCallName: 'client.core.analytics.updateScheduleAttainment',
    fullyQualifiedName: 'core.analytics.updateScheduleAttainment',
    httpMethod: 'put',
    httpPath: '/v1/core/analytics/schedule-attainment',
  },
  {
    clientCallName: 'client.core.analytics.updateDeliveryPerformance',
    fullyQualifiedName: 'core.analytics.updateDeliveryPerformance',
    httpMethod: 'put',
    httpPath: '/v1/core/analytics/delivery-performance',
  },
  {
    clientCallName: 'client.core.actions.emailRecord',
    fullyQualifiedName: 'core.actions.emailRecord',
    httpMethod: 'post',
    httpPath: '/v1/core/actions/email-record',
  },
  {
    clientCallName: 'client.catalog.units.list',
    fullyQualifiedName: 'catalog.units.list',
    httpMethod: 'get',
    httpPath: '/v1/catalog/units',
  },
  {
    clientCallName: 'client.catalog.units.retrieve',
    fullyQualifiedName: 'catalog.units.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/catalog/units/{id}',
  },
  {
    clientCallName: 'client.catalog.units.create',
    fullyQualifiedName: 'catalog.units.create',
    httpMethod: 'post',
    httpPath: '/v1/catalog/units',
  },
  {
    clientCallName: 'client.catalog.units.update',
    fullyQualifiedName: 'catalog.units.update',
    httpMethod: 'patch',
    httpPath: '/v1/catalog/units/{id}',
  },
  {
    clientCallName: 'client.catalog.units.delete',
    fullyQualifiedName: 'catalog.units.delete',
    httpMethod: 'delete',
    httpPath: '/v1/catalog/units/{id}',
  },
  {
    clientCallName: 'client.catalog.units.actions.bulkUpsert',
    fullyQualifiedName: 'catalog.units.actions.bulkUpsert',
    httpMethod: 'post',
    httpPath: '/v1/catalog/units/actions/bulk-upsert',
  },
  {
    clientCallName: 'client.catalog.unitGroups.list',
    fullyQualifiedName: 'catalog.unitGroups.list',
    httpMethod: 'get',
    httpPath: '/v1/catalog/unit-groups',
  },
  {
    clientCallName: 'client.catalog.unitGroups.retrieve',
    fullyQualifiedName: 'catalog.unitGroups.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/catalog/unit-groups/{id}',
  },
  {
    clientCallName: 'client.catalog.unitGroups.create',
    fullyQualifiedName: 'catalog.unitGroups.create',
    httpMethod: 'post',
    httpPath: '/v1/catalog/unit-groups',
  },
  {
    clientCallName: 'client.catalog.unitGroups.update',
    fullyQualifiedName: 'catalog.unitGroups.update',
    httpMethod: 'patch',
    httpPath: '/v1/catalog/unit-groups/{id}',
  },
  {
    clientCallName: 'client.catalog.unitGroups.delete',
    fullyQualifiedName: 'catalog.unitGroups.delete',
    httpMethod: 'delete',
    httpPath: '/v1/catalog/unit-groups/{id}',
  },
  {
    clientCallName: 'client.catalog.unitGroups.units.list',
    fullyQualifiedName: 'catalog.unitGroups.units.list',
    httpMethod: 'get',
    httpPath: '/v1/catalog/unit-groups/{unit_group_id}/units',
  },
  {
    clientCallName: 'client.catalog.unitGroups.units.retrieve',
    fullyQualifiedName: 'catalog.unitGroups.units.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/catalog/unit-groups/{unit_group_id}/units/{id}',
  },
  {
    clientCallName: 'client.catalog.unitGroups.units.create',
    fullyQualifiedName: 'catalog.unitGroups.units.create',
    httpMethod: 'post',
    httpPath: '/v1/catalog/unit-groups/{unit_group_id}/units',
  },
  {
    clientCallName: 'client.catalog.unitGroups.units.update',
    fullyQualifiedName: 'catalog.unitGroups.units.update',
    httpMethod: 'patch',
    httpPath: '/v1/catalog/unit-groups/{unit_group_id}/units/{id}',
  },
  {
    clientCallName: 'client.catalog.unitGroups.units.delete',
    fullyQualifiedName: 'catalog.unitGroups.units.delete',
    httpMethod: 'delete',
    httpPath: '/v1/catalog/unit-groups/{unit_group_id}/units/{id}',
  },
  {
    clientCallName: 'client.catalog.unitGroups.actions.bulkUpsert',
    fullyQualifiedName: 'catalog.unitGroups.actions.bulkUpsert',
    httpMethod: 'post',
    httpPath: '/v1/catalog/unit-groups/actions/bulk-upsert',
  },
  {
    clientCallName: 'client.catalog.properties.list',
    fullyQualifiedName: 'catalog.properties.list',
    httpMethod: 'get',
    httpPath: '/v1/catalog/properties',
  },
  {
    clientCallName: 'client.catalog.properties.retrieve',
    fullyQualifiedName: 'catalog.properties.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/catalog/properties/{id}',
  },
  {
    clientCallName: 'client.catalog.properties.create',
    fullyQualifiedName: 'catalog.properties.create',
    httpMethod: 'post',
    httpPath: '/v1/catalog/properties',
  },
  {
    clientCallName: 'client.catalog.properties.update',
    fullyQualifiedName: 'catalog.properties.update',
    httpMethod: 'patch',
    httpPath: '/v1/catalog/properties/{id}',
  },
  {
    clientCallName: 'client.catalog.properties.delete',
    fullyQualifiedName: 'catalog.properties.delete',
    httpMethod: 'delete',
    httpPath: '/v1/catalog/properties/{id}',
  },
  {
    clientCallName: 'client.catalog.properties.attributes.list',
    fullyQualifiedName: 'catalog.properties.attributes.list',
    httpMethod: 'get',
    httpPath: '/v1/catalog/properties/{property_id}/attributes',
  },
  {
    clientCallName: 'client.catalog.properties.attributes.retrieve',
    fullyQualifiedName: 'catalog.properties.attributes.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/catalog/properties/{property_id}/attributes/{id}',
  },
  {
    clientCallName: 'client.catalog.properties.attributes.create',
    fullyQualifiedName: 'catalog.properties.attributes.create',
    httpMethod: 'post',
    httpPath: '/v1/catalog/properties/{property_id}/attributes',
  },
  {
    clientCallName: 'client.catalog.properties.attributes.update',
    fullyQualifiedName: 'catalog.properties.attributes.update',
    httpMethod: 'patch',
    httpPath: '/v1/catalog/properties/{property_id}/attributes/{id}',
  },
  {
    clientCallName: 'client.catalog.properties.attributes.delete',
    fullyQualifiedName: 'catalog.properties.attributes.delete',
    httpMethod: 'delete',
    httpPath: '/v1/catalog/properties/{property_id}/attributes/{id}',
  },
  {
    clientCallName: 'client.catalog.properties.actions.bulkUpsert',
    fullyQualifiedName: 'catalog.properties.actions.bulkUpsert',
    httpMethod: 'post',
    httpPath: '/v1/catalog/properties/actions/bulk-upsert',
  },
  {
    clientCallName: 'client.catalog.items.list',
    fullyQualifiedName: 'catalog.items.list',
    httpMethod: 'get',
    httpPath: '/v1/catalog/items',
  },
  {
    clientCallName: 'client.catalog.items.retrieve',
    fullyQualifiedName: 'catalog.items.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/catalog/items/{id}',
  },
  {
    clientCallName: 'client.catalog.items.retrieveLotDefault',
    fullyQualifiedName: 'catalog.items.retrieveLotDefault',
    httpMethod: 'get',
    httpPath: '/v1/catalog/items/{id}/lot-default',
  },
  {
    clientCallName: 'client.catalog.items.changeCategory',
    fullyQualifiedName: 'catalog.items.changeCategory',
    httpMethod: 'put',
    httpPath: '/v1/catalog/items/{id}/category/{category_id}',
  },
  {
    clientCallName: 'client.catalog.items.inventory.list',
    fullyQualifiedName: 'catalog.items.inventory.list',
    httpMethod: 'get',
    httpPath: '/v1/catalog/items/{id}/inventory',
  },
  {
    clientCallName: 'client.catalog.items.inventory.update',
    fullyQualifiedName: 'catalog.items.inventory.update',
    httpMethod: 'patch',
    httpPath: '/v1/catalog/items/{id}/inventory',
  },
  {
    clientCallName: 'client.catalog.items.attributes.update',
    fullyQualifiedName: 'catalog.items.attributes.update',
    httpMethod: 'put',
    httpPath: '/v1/catalog/items/{id}/attributes/{attribute_id}',
  },
  {
    clientCallName: 'client.catalog.items.attributes.delete',
    fullyQualifiedName: 'catalog.items.attributes.delete',
    httpMethod: 'delete',
    httpPath: '/v1/catalog/items/{id}/attributes/{attribute_id}',
  },
  {
    clientCallName: 'client.catalog.items.actions.bulkReconcile',
    fullyQualifiedName: 'catalog.items.actions.bulkReconcile',
    httpMethod: 'post',
    httpPath: '/v1/catalog/items/actions/bulk-reconcile',
  },
  {
    clientCallName: 'client.catalog.itemCategories.list',
    fullyQualifiedName: 'catalog.itemCategories.list',
    httpMethod: 'get',
    httpPath: '/v1/catalog/item-categories',
  },
  {
    clientCallName: 'client.catalog.itemCategories.retrieve',
    fullyQualifiedName: 'catalog.itemCategories.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/catalog/item-categories/{id}',
  },
  {
    clientCallName: 'client.catalog.itemCategories.create',
    fullyQualifiedName: 'catalog.itemCategories.create',
    httpMethod: 'post',
    httpPath: '/v1/catalog/item-categories',
  },
  {
    clientCallName: 'client.catalog.itemCategories.update',
    fullyQualifiedName: 'catalog.itemCategories.update',
    httpMethod: 'patch',
    httpPath: '/v1/catalog/item-categories/{id}',
  },
  {
    clientCallName: 'client.catalog.itemCategories.delete',
    fullyQualifiedName: 'catalog.itemCategories.delete',
    httpMethod: 'delete',
    httpPath: '/v1/catalog/item-categories/{id}',
  },
  {
    clientCallName: 'client.catalog.itemCategories.changeUnitGroup',
    fullyQualifiedName: 'catalog.itemCategories.changeUnitGroup',
    httpMethod: 'put',
    httpPath: '/v1/catalog/item-categories/{id}/unit-groups/{unit_group_id}',
  },
  {
    clientCallName: 'client.catalog.itemCategories.properties.update',
    fullyQualifiedName: 'catalog.itemCategories.properties.update',
    httpMethod: 'put',
    httpPath: '/v1/catalog/item-categories/{id}/properties/{property_id}',
  },
  {
    clientCallName: 'client.catalog.itemCategories.properties.create',
    fullyQualifiedName: 'catalog.itemCategories.properties.create',
    httpMethod: 'post',
    httpPath: '/v1/catalog/item-categories/{id}/properties',
  },
  {
    clientCallName: 'client.catalog.itemCategories.properties.delete',
    fullyQualifiedName: 'catalog.itemCategories.properties.delete',
    httpMethod: 'delete',
    httpPath: '/v1/catalog/item-categories/{id}/properties/{property_id}',
  },
  {
    clientCallName: 'client.catalog.itemCategories.actions.bulkUpsert',
    fullyQualifiedName: 'catalog.itemCategories.actions.bulkUpsert',
    httpMethod: 'post',
    httpPath: '/v1/catalog/item-categories/actions/bulk-upsert',
  },
  {
    clientCallName: 'client.catalog.materials.list',
    fullyQualifiedName: 'catalog.materials.list',
    httpMethod: 'get',
    httpPath: '/v1/catalog/materials',
  },
  {
    clientCallName: 'client.catalog.materials.retrieve',
    fullyQualifiedName: 'catalog.materials.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/catalog/materials/{id}',
  },
  {
    clientCallName: 'client.catalog.materials.create',
    fullyQualifiedName: 'catalog.materials.create',
    httpMethod: 'post',
    httpPath: '/v1/catalog/materials',
  },
  {
    clientCallName: 'client.catalog.materials.update',
    fullyQualifiedName: 'catalog.materials.update',
    httpMethod: 'patch',
    httpPath: '/v1/catalog/materials/{id}',
  },
  {
    clientCallName: 'client.catalog.materials.delete',
    fullyQualifiedName: 'catalog.materials.delete',
    httpMethod: 'delete',
    httpPath: '/v1/catalog/materials/{id}',
  },
  {
    clientCallName: 'client.catalog.materials.actions.bulkUpsert',
    fullyQualifiedName: 'catalog.materials.actions.bulkUpsert',
    httpMethod: 'post',
    httpPath: '/v1/catalog/materials/actions/bulk-upsert',
  },
  {
    clientCallName: 'client.catalog.parts.list',
    fullyQualifiedName: 'catalog.parts.list',
    httpMethod: 'get',
    httpPath: '/v1/catalog/parts',
  },
  {
    clientCallName: 'client.catalog.parts.retrieve',
    fullyQualifiedName: 'catalog.parts.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/catalog/parts/{id}',
  },
  {
    clientCallName: 'client.catalog.parts.create',
    fullyQualifiedName: 'catalog.parts.create',
    httpMethod: 'post',
    httpPath: '/v1/catalog/parts',
  },
  {
    clientCallName: 'client.catalog.parts.update',
    fullyQualifiedName: 'catalog.parts.update',
    httpMethod: 'patch',
    httpPath: '/v1/catalog/parts/{id}',
  },
  {
    clientCallName: 'client.catalog.parts.delete',
    fullyQualifiedName: 'catalog.parts.delete',
    httpMethod: 'delete',
    httpPath: '/v1/catalog/parts/{id}',
  },
  {
    clientCallName: 'client.catalog.parts.actions.bulkUpsert',
    fullyQualifiedName: 'catalog.parts.actions.bulkUpsert',
    httpMethod: 'post',
    httpPath: '/v1/catalog/parts/actions/bulk-upsert',
  },
  {
    clientCallName: 'client.catalog.productLines.list',
    fullyQualifiedName: 'catalog.productLines.list',
    httpMethod: 'get',
    httpPath: '/v1/catalog/product-lines',
  },
  {
    clientCallName: 'client.catalog.productLines.retrieve',
    fullyQualifiedName: 'catalog.productLines.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/catalog/product-lines/{id}',
  },
  {
    clientCallName: 'client.catalog.productLines.create',
    fullyQualifiedName: 'catalog.productLines.create',
    httpMethod: 'post',
    httpPath: '/v1/catalog/product-lines',
  },
  {
    clientCallName: 'client.catalog.productLines.update',
    fullyQualifiedName: 'catalog.productLines.update',
    httpMethod: 'patch',
    httpPath: '/v1/catalog/product-lines/{id}',
  },
  {
    clientCallName: 'client.catalog.productLines.delete',
    fullyQualifiedName: 'catalog.productLines.delete',
    httpMethod: 'delete',
    httpPath: '/v1/catalog/product-lines/{id}',
  },
  {
    clientCallName: 'client.catalog.productLines.actions.bulkUpsert',
    fullyQualifiedName: 'catalog.productLines.actions.bulkUpsert',
    httpMethod: 'post',
    httpPath: '/v1/catalog/product-lines/actions/bulk-upsert',
  },
  {
    clientCallName: 'client.catalog.products.list',
    fullyQualifiedName: 'catalog.products.list',
    httpMethod: 'get',
    httpPath: '/v1/catalog/products',
  },
  {
    clientCallName: 'client.catalog.products.retrieve',
    fullyQualifiedName: 'catalog.products.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/catalog/products/{id}',
  },
  {
    clientCallName: 'client.catalog.products.create',
    fullyQualifiedName: 'catalog.products.create',
    httpMethod: 'post',
    httpPath: '/v1/catalog/products',
  },
  {
    clientCallName: 'client.catalog.products.update',
    fullyQualifiedName: 'catalog.products.update',
    httpMethod: 'patch',
    httpPath: '/v1/catalog/products/{id}',
  },
  {
    clientCallName: 'client.catalog.products.delete',
    fullyQualifiedName: 'catalog.products.delete',
    httpMethod: 'delete',
    httpPath: '/v1/catalog/products/{id}',
  },
  {
    clientCallName: 'client.catalog.products.changeProductLine',
    fullyQualifiedName: 'catalog.products.changeProductLine',
    httpMethod: 'put',
    httpPath: '/v1/catalog/products/{id}/product-line/{product_line_id}',
  },
  {
    clientCallName: 'client.catalog.products.actions.bulkUpsert',
    fullyQualifiedName: 'catalog.products.actions.bulkUpsert',
    httpMethod: 'post',
    httpPath: '/v1/catalog/products/actions/bulk-upsert',
  },
  {
    clientCallName: 'client.ai.retrieveTools',
    fullyQualifiedName: 'ai.retrieveTools',
    httpMethod: 'get',
    httpPath: '/v1/ai/tools',
  },
  {
    clientCallName: 'client.ai.retrieveToolGroups',
    fullyQualifiedName: 'ai.retrieveToolGroups',
    httpMethod: 'get',
    httpPath: '/v1/ai/tool-groups',
  },
  {
    clientCallName: 'client.ai.agents.create',
    fullyQualifiedName: 'ai.agents.create',
    httpMethod: 'post',
    httpPath: '/v1/ai/agents',
  },
  {
    clientCallName: 'client.ai.agents.list',
    fullyQualifiedName: 'ai.agents.list',
    httpMethod: 'get',
    httpPath: '/v1/ai/agents',
  },
  {
    clientCallName: 'client.ai.agents.retrieve',
    fullyQualifiedName: 'ai.agents.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/ai/agents/{id}',
  },
  {
    clientCallName: 'client.ai.agents.update',
    fullyQualifiedName: 'ai.agents.update',
    httpMethod: 'patch',
    httpPath: '/v1/ai/agents/{id}',
  },
  {
    clientCallName: 'client.ai.agents.delete',
    fullyQualifiedName: 'ai.agents.delete',
    httpMethod: 'delete',
    httpPath: '/v1/ai/agents/{id}',
  },
  {
    clientCallName: 'client.ai.agents.updateStatus',
    fullyQualifiedName: 'ai.agents.updateStatus',
    httpMethod: 'put',
    httpPath: '/v1/ai/agents/{id}/status',
  },
  {
    clientCallName: 'client.ai.runs.list',
    fullyQualifiedName: 'ai.runs.list',
    httpMethod: 'get',
    httpPath: '/v1/ai/runs',
  },
  {
    clientCallName: 'client.ai.runs.retrieve',
    fullyQualifiedName: 'ai.runs.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/ai/runs/{id}',
  },
  {
    clientCallName: 'client.ai.runs.create',
    fullyQualifiedName: 'ai.runs.create',
    httpMethod: 'post',
    httpPath: '/v1/ai/runs',
  },
  {
    clientCallName: 'client.ai.runs.actions.cancel',
    fullyQualifiedName: 'ai.runs.actions.cancel',
    httpMethod: 'post',
    httpPath: '/v1/ai/runs/{id}/actions/cancel',
  },
  {
    clientCallName: 'client.ai.runs.actions.continue',
    fullyQualifiedName: 'ai.runs.actions.continue',
    httpMethod: 'post',
    httpPath: '/v1/ai/runs/{id}/actions/continue',
  },
  {
    clientCallName: 'client.ai.runs.actions.retry',
    fullyQualifiedName: 'ai.runs.actions.retry',
    httpMethod: 'post',
    httpPath: '/v1/ai/runs/{id}/actions/retry',
  },
  {
    clientCallName: 'client.ai.memories.list',
    fullyQualifiedName: 'ai.memories.list',
    httpMethod: 'get',
    httpPath: '/v1/ai/memories',
  },
  {
    clientCallName: 'client.ai.memories.retrieve',
    fullyQualifiedName: 'ai.memories.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/ai/memories/{id}',
  },
  {
    clientCallName: 'client.ai.memories.create',
    fullyQualifiedName: 'ai.memories.create',
    httpMethod: 'post',
    httpPath: '/v1/ai/memories',
  },
  {
    clientCallName: 'client.ai.memories.update',
    fullyQualifiedName: 'ai.memories.update',
    httpMethod: 'patch',
    httpPath: '/v1/ai/memories/{id}',
  },
  {
    clientCallName: 'client.ai.memories.delete',
    fullyQualifiedName: 'ai.memories.delete',
    httpMethod: 'delete',
    httpPath: '/v1/ai/memories/{id}',
  },
  {
    clientCallName: 'client.messaging.retrieveContacts',
    fullyQualifiedName: 'messaging.retrieveContacts',
    httpMethod: 'get',
    httpPath: '/v1/messaging/contacts',
  },
  {
    clientCallName: 'client.messaging.notifications.create',
    fullyQualifiedName: 'messaging.notifications.create',
    httpMethod: 'post',
    httpPath: '/v1/messaging/notifications',
  },
  {
    clientCallName: 'client.messaging.notifications.list',
    fullyQualifiedName: 'messaging.notifications.list',
    httpMethod: 'get',
    httpPath: '/v1/messaging/notifications',
  },
  {
    clientCallName: 'client.messaging.notifications.retrieve',
    fullyQualifiedName: 'messaging.notifications.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/messaging/notifications/{id}',
  },
  {
    clientCallName: 'client.messaging.notifications.retrieveUnreadCount',
    fullyQualifiedName: 'messaging.notifications.retrieveUnreadCount',
    httpMethod: 'get',
    httpPath: '/v1/messaging/notifications/unread-count',
  },
  {
    clientCallName: 'client.messaging.notifications.retrieveUnreadSummary',
    fullyQualifiedName: 'messaging.notifications.retrieveUnreadSummary',
    httpMethod: 'get',
    httpPath: '/v1/messaging/notifications/unread-summary',
  },
  {
    clientCallName: 'client.messaging.notifications.actions.seen',
    fullyQualifiedName: 'messaging.notifications.actions.seen',
    httpMethod: 'post',
    httpPath: '/v1/messaging/notifications/{id}/actions/seen',
  },
  {
    clientCallName: 'client.messaging.notifications.actions.read',
    fullyQualifiedName: 'messaging.notifications.actions.read',
    httpMethod: 'post',
    httpPath: '/v1/messaging/notifications/{id}/actions/read',
  },
  {
    clientCallName: 'client.messaging.notifications.actions.dismiss',
    fullyQualifiedName: 'messaging.notifications.actions.dismiss',
    httpMethod: 'post',
    httpPath: '/v1/messaging/notifications/{id}/actions/dismiss',
  },
  {
    clientCallName: 'client.messaging.notifications.actions.markAllSeen',
    fullyQualifiedName: 'messaging.notifications.actions.markAllSeen',
    httpMethod: 'post',
    httpPath: '/v1/messaging/notifications/actions/mark-all-seen',
  },
  {
    clientCallName: 'client.messaging.announcements.list',
    fullyQualifiedName: 'messaging.announcements.list',
    httpMethod: 'get',
    httpPath: '/v1/messaging/announcements',
  },
  {
    clientCallName: 'client.messaging.announcements.retrieve',
    fullyQualifiedName: 'messaging.announcements.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/messaging/announcements/{id}',
  },
  {
    clientCallName: 'client.messaging.announcements.actions.seen',
    fullyQualifiedName: 'messaging.announcements.actions.seen',
    httpMethod: 'post',
    httpPath: '/v1/messaging/announcements/{id}/actions/seen',
  },
  {
    clientCallName: 'client.messaging.announcements.actions.read',
    fullyQualifiedName: 'messaging.announcements.actions.read',
    httpMethod: 'post',
    httpPath: '/v1/messaging/announcements/{id}/actions/read',
  },
  {
    clientCallName: 'client.messaging.announcements.actions.dismiss',
    fullyQualifiedName: 'messaging.announcements.actions.dismiss',
    httpMethod: 'post',
    httpPath: '/v1/messaging/announcements/{id}/actions/dismiss',
  },
  {
    clientCallName: 'client.messaging.conversations.create',
    fullyQualifiedName: 'messaging.conversations.create',
    httpMethod: 'post',
    httpPath: '/v1/messaging/conversations',
  },
  {
    clientCallName: 'client.messaging.conversations.list',
    fullyQualifiedName: 'messaging.conversations.list',
    httpMethod: 'get',
    httpPath: '/v1/messaging/conversations',
  },
  {
    clientCallName: 'client.messaging.conversations.retrieve',
    fullyQualifiedName: 'messaging.conversations.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/messaging/conversations/{id}',
  },
  {
    clientCallName: 'client.messaging.conversations.update',
    fullyQualifiedName: 'messaging.conversations.update',
    httpMethod: 'patch',
    httpPath: '/v1/messaging/conversations/{id}',
  },
  {
    clientCallName: 'client.messaging.conversations.actions.setLegalHold',
    fullyQualifiedName: 'messaging.conversations.actions.setLegalHold',
    httpMethod: 'post',
    httpPath: '/v1/messaging/conversations/{id}/actions/set-legal-hold',
  },
  {
    clientCallName: 'client.messaging.conversations.actions.redact',
    fullyQualifiedName: 'messaging.conversations.actions.redact',
    httpMethod: 'post',
    httpPath: '/v1/messaging/conversations/{id}/actions/redact',
  },
  {
    clientCallName: 'client.messaging.conversations.actions.read',
    fullyQualifiedName: 'messaging.conversations.actions.read',
    httpMethod: 'post',
    httpPath: '/v1/messaging/conversations/{id}/actions/read',
  },
  {
    clientCallName: 'client.messaging.conversations.actions.archive',
    fullyQualifiedName: 'messaging.conversations.actions.archive',
    httpMethod: 'post',
    httpPath: '/v1/messaging/conversations/{id}/actions/archive',
  },
  {
    clientCallName: 'client.messaging.conversations.actions.unarchive',
    fullyQualifiedName: 'messaging.conversations.actions.unarchive',
    httpMethod: 'post',
    httpPath: '/v1/messaging/conversations/{id}/actions/unarchive',
  },
  {
    clientCallName: 'client.messaging.conversations.actions.leave',
    fullyQualifiedName: 'messaging.conversations.actions.leave',
    httpMethod: 'post',
    httpPath: '/v1/messaging/conversations/{id}/actions/leave',
  },
  {
    clientCallName: 'client.messaging.conversations.actions.hide',
    fullyQualifiedName: 'messaging.conversations.actions.hide',
    httpMethod: 'post',
    httpPath: '/v1/messaging/conversations/{id}/actions/hide',
  },
  {
    clientCallName: 'client.messaging.conversations.actions.unhide',
    fullyQualifiedName: 'messaging.conversations.actions.unhide',
    httpMethod: 'post',
    httpPath: '/v1/messaging/conversations/{id}/actions/unhide',
  },
  {
    clientCallName: 'client.messaging.conversations.actions.mute',
    fullyQualifiedName: 'messaging.conversations.actions.mute',
    httpMethod: 'post',
    httpPath: '/v1/messaging/conversations/{id}/actions/mute',
  },
  {
    clientCallName: 'client.messaging.conversations.actions.unmute',
    fullyQualifiedName: 'messaging.conversations.actions.unmute',
    httpMethod: 'post',
    httpPath: '/v1/messaging/conversations/{id}/actions/unmute',
  },
  {
    clientCallName: 'client.messaging.conversations.actions.setStatus',
    fullyQualifiedName: 'messaging.conversations.actions.setStatus',
    httpMethod: 'post',
    httpPath: '/v1/messaging/conversations/{id}/actions/set-status',
  },
  {
    clientCallName: 'client.messaging.conversations.actions.assign',
    fullyQualifiedName: 'messaging.conversations.actions.assign',
    httpMethod: 'post',
    httpPath: '/v1/messaging/conversations/{id}/actions/assign',
  },
  {
    clientCallName: 'client.messaging.conversations.actions.report',
    fullyQualifiedName: 'messaging.conversations.actions.report',
    httpMethod: 'post',
    httpPath: '/v1/messaging/conversations/{id}/actions/report',
  },
  {
    clientCallName: 'client.messaging.conversations.links.create',
    fullyQualifiedName: 'messaging.conversations.links.create',
    httpMethod: 'post',
    httpPath: '/v1/messaging/conversations/{id}/links',
  },
  {
    clientCallName: 'client.messaging.conversations.links.delete',
    fullyQualifiedName: 'messaging.conversations.links.delete',
    httpMethod: 'delete',
    httpPath: '/v1/messaging/conversations/{id}/links/{link_id}',
  },
  {
    clientCallName: 'client.messaging.conversations.links.list',
    fullyQualifiedName: 'messaging.conversations.links.list',
    httpMethod: 'get',
    httpPath: '/v1/messaging/conversations/{id}/links',
  },
  {
    clientCallName: 'client.messaging.conversations.messages.create',
    fullyQualifiedName: 'messaging.conversations.messages.create',
    httpMethod: 'post',
    httpPath: '/v1/messaging/conversations/{id}/messages',
  },
  {
    clientCallName: 'client.messaging.conversations.messages.list',
    fullyQualifiedName: 'messaging.conversations.messages.list',
    httpMethod: 'get',
    httpPath: '/v1/messaging/conversations/{id}/messages',
  },
  {
    clientCallName: 'client.messaging.conversations.participants.create',
    fullyQualifiedName: 'messaging.conversations.participants.create',
    httpMethod: 'post',
    httpPath: '/v1/messaging/conversations/{id}/participants',
  },
  {
    clientCallName: 'client.messaging.conversations.participants.delete',
    fullyQualifiedName: 'messaging.conversations.participants.delete',
    httpMethod: 'delete',
    httpPath: '/v1/messaging/conversations/{id}/participants/{pid}',
  },
  {
    clientCallName: 'client.messaging.conversations.participants.actions.setRole',
    fullyQualifiedName: 'messaging.conversations.participants.actions.setRole',
    httpMethod: 'post',
    httpPath: '/v1/messaging/conversations/{id}/participants/{pid}/actions/set-role',
  },
  {
    clientCallName: 'client.messaging.conversations.attachments.actions.uploadURL',
    fullyQualifiedName: 'messaging.conversations.attachments.actions.uploadURL',
    httpMethod: 'post',
    httpPath: '/v1/messaging/conversations/{id}/attachments/actions/upload-url',
  },
  {
    clientCallName: 'client.messaging.messages.update',
    fullyQualifiedName: 'messaging.messages.update',
    httpMethod: 'patch',
    httpPath: '/v1/messaging/messages/{id}',
  },
  {
    clientCallName: 'client.messaging.messages.actions.approveSend',
    fullyQualifiedName: 'messaging.messages.actions.approveSend',
    httpMethod: 'post',
    httpPath: '/v1/messaging/messages/{id}/actions/approve-send',
  },
  {
    clientCallName: 'client.messaging.messages.actions.reject',
    fullyQualifiedName: 'messaging.messages.actions.reject',
    httpMethod: 'post',
    httpPath: '/v1/messaging/messages/{id}/actions/reject',
  },
  {
    clientCallName: 'client.messaging.messages.actions.cancel',
    fullyQualifiedName: 'messaging.messages.actions.cancel',
    httpMethod: 'post',
    httpPath: '/v1/messaging/messages/{id}/actions/cancel',
  },
  {
    clientCallName: 'client.messaging.messages.actions.reschedule',
    fullyQualifiedName: 'messaging.messages.actions.reschedule',
    httpMethod: 'post',
    httpPath: '/v1/messaging/messages/{id}/actions/reschedule',
  },
  {
    clientCallName: 'client.messaging.groups.create',
    fullyQualifiedName: 'messaging.groups.create',
    httpMethod: 'post',
    httpPath: '/v1/messaging/groups',
  },
  {
    clientCallName: 'client.messaging.groups.list',
    fullyQualifiedName: 'messaging.groups.list',
    httpMethod: 'get',
    httpPath: '/v1/messaging/groups',
  },
  {
    clientCallName: 'client.messaging.groups.retrieve',
    fullyQualifiedName: 'messaging.groups.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/messaging/groups/{id}',
  },
  {
    clientCallName: 'client.messaging.groups.update',
    fullyQualifiedName: 'messaging.groups.update',
    httpMethod: 'patch',
    httpPath: '/v1/messaging/groups/{id}',
  },
  {
    clientCallName: 'client.messaging.groups.delete',
    fullyQualifiedName: 'messaging.groups.delete',
    httpMethod: 'delete',
    httpPath: '/v1/messaging/groups/{id}',
  },
  {
    clientCallName: 'client.messaging.groups.members.create',
    fullyQualifiedName: 'messaging.groups.members.create',
    httpMethod: 'post',
    httpPath: '/v1/messaging/groups/{id}/members',
  },
  {
    clientCallName: 'client.messaging.groups.members.delete',
    fullyQualifiedName: 'messaging.groups.members.delete',
    httpMethod: 'delete',
    httpPath: '/v1/messaging/groups/{id}/members/{member_id}',
  },
  {
    clientCallName: 'client.messaging.blocks.create',
    fullyQualifiedName: 'messaging.blocks.create',
    httpMethod: 'post',
    httpPath: '/v1/messaging/blocks',
  },
  {
    clientCallName: 'client.messaging.blocks.delete',
    fullyQualifiedName: 'messaging.blocks.delete',
    httpMethod: 'delete',
    httpPath: '/v1/messaging/blocks/{id}',
  },
  {
    clientCallName: 'client.messaging.blocks.list',
    fullyQualifiedName: 'messaging.blocks.list',
    httpMethod: 'get',
    httpPath: '/v1/messaging/blocks',
  },
  {
    clientCallName: 'client.messaging.preferences.list',
    fullyQualifiedName: 'messaging.preferences.list',
    httpMethod: 'get',
    httpPath: '/v1/messaging/preferences',
  },
  {
    clientCallName: 'client.messaging.preferences.update',
    fullyQualifiedName: 'messaging.preferences.update',
    httpMethod: 'put',
    httpPath: '/v1/messaging/preferences',
  },
  {
    clientCallName: 'client.messaging.emailDomains.create',
    fullyQualifiedName: 'messaging.emailDomains.create',
    httpMethod: 'post',
    httpPath: '/v1/messaging/email-domains',
  },
  {
    clientCallName: 'client.messaging.emailDomains.list',
    fullyQualifiedName: 'messaging.emailDomains.list',
    httpMethod: 'get',
    httpPath: '/v1/messaging/email-domains',
  },
  {
    clientCallName: 'client.messaging.emailDomains.retrieve',
    fullyQualifiedName: 'messaging.emailDomains.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/messaging/email-domains/{id}',
  },
  {
    clientCallName: 'client.messaging.emailDomains.delete',
    fullyQualifiedName: 'messaging.emailDomains.delete',
    httpMethod: 'delete',
    httpPath: '/v1/messaging/email-domains/{id}',
  },
  {
    clientCallName: 'client.messaging.emailDomains.actions.verify',
    fullyQualifiedName: 'messaging.emailDomains.actions.verify',
    httpMethod: 'post',
    httpPath: '/v1/messaging/email-domains/{id}/actions/verify',
  },
  {
    clientCallName: 'client.messaging.emailInboxes.create',
    fullyQualifiedName: 'messaging.emailInboxes.create',
    httpMethod: 'post',
    httpPath: '/v1/messaging/email-inboxes',
  },
  {
    clientCallName: 'client.messaging.emailInboxes.list',
    fullyQualifiedName: 'messaging.emailInboxes.list',
    httpMethod: 'get',
    httpPath: '/v1/messaging/email-inboxes',
  },
  {
    clientCallName: 'client.messaging.emailInboxes.retrieve',
    fullyQualifiedName: 'messaging.emailInboxes.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/messaging/email-inboxes/{id}',
  },
  {
    clientCallName: 'client.messaging.emailInboxes.update',
    fullyQualifiedName: 'messaging.emailInboxes.update',
    httpMethod: 'patch',
    httpPath: '/v1/messaging/email-inboxes/{id}',
  },
  {
    clientCallName: 'client.messaging.emailInboxes.delete',
    fullyQualifiedName: 'messaging.emailInboxes.delete',
    httpMethod: 'delete',
    httpPath: '/v1/messaging/email-inboxes/{id}',
  },
  {
    clientCallName: 'client.messaging.emailSender.list',
    fullyQualifiedName: 'messaging.emailSender.list',
    httpMethod: 'get',
    httpPath: '/v1/messaging/email-sender',
  },
  {
    clientCallName: 'client.messaging.emailSender.update',
    fullyQualifiedName: 'messaging.emailSender.update',
    httpMethod: 'put',
    httpPath: '/v1/messaging/email-sender',
  },
  {
    clientCallName: 'client.messaging.emailSender.delete',
    fullyQualifiedName: 'messaging.emailSender.delete',
    httpMethod: 'delete',
    httpPath: '/v1/messaging/email-sender',
  },
  {
    clientCallName: 'client.sales.accountGroups.list',
    fullyQualifiedName: 'sales.accountGroups.list',
    httpMethod: 'get',
    httpPath: '/v1/sales/account-groups',
  },
  {
    clientCallName: 'client.sales.accountGroups.retrieve',
    fullyQualifiedName: 'sales.accountGroups.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/sales/account-groups/{id}',
  },
  {
    clientCallName: 'client.sales.accountGroups.create',
    fullyQualifiedName: 'sales.accountGroups.create',
    httpMethod: 'post',
    httpPath: '/v1/sales/account-groups',
  },
  {
    clientCallName: 'client.sales.accountGroups.update',
    fullyQualifiedName: 'sales.accountGroups.update',
    httpMethod: 'patch',
    httpPath: '/v1/sales/account-groups/{id}',
  },
  {
    clientCallName: 'client.sales.accountGroups.delete',
    fullyQualifiedName: 'sales.accountGroups.delete',
    httpMethod: 'delete',
    httpPath: '/v1/sales/account-groups/{id}',
  },
  {
    clientCallName: 'client.sales.accountPrices.list',
    fullyQualifiedName: 'sales.accountPrices.list',
    httpMethod: 'get',
    httpPath: '/v1/sales/account-prices',
  },
  {
    clientCallName: 'client.sales.accountPrices.retrieve',
    fullyQualifiedName: 'sales.accountPrices.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/sales/account-prices/{id}',
  },
  {
    clientCallName: 'client.sales.accountPrices.create',
    fullyQualifiedName: 'sales.accountPrices.create',
    httpMethod: 'post',
    httpPath: '/v1/sales/account-prices',
  },
  {
    clientCallName: 'client.sales.accountPrices.update',
    fullyQualifiedName: 'sales.accountPrices.update',
    httpMethod: 'patch',
    httpPath: '/v1/sales/account-prices/{id}',
  },
  {
    clientCallName: 'client.sales.accountPrices.delete',
    fullyQualifiedName: 'sales.accountPrices.delete',
    httpMethod: 'delete',
    httpPath: '/v1/sales/account-prices/{id}',
  },
  {
    clientCallName: 'client.sales.accountPrices.actions.exportPriceList',
    fullyQualifiedName: 'sales.accountPrices.actions.exportPriceList',
    httpMethod: 'post',
    httpPath: '/v1/sales/account-prices/actions/export-price-list',
  },
  {
    clientCallName: 'client.sales.addresses.list',
    fullyQualifiedName: 'sales.addresses.list',
    httpMethod: 'get',
    httpPath: '/v1/sales/addresses',
  },
  {
    clientCallName: 'client.sales.addresses.retrieve',
    fullyQualifiedName: 'sales.addresses.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/sales/addresses/{id}',
  },
  {
    clientCallName: 'client.sales.addresses.create',
    fullyQualifiedName: 'sales.addresses.create',
    httpMethod: 'post',
    httpPath: '/v1/sales/addresses',
  },
  {
    clientCallName: 'client.sales.addresses.update',
    fullyQualifiedName: 'sales.addresses.update',
    httpMethod: 'patch',
    httpPath: '/v1/sales/addresses/{id}',
  },
  {
    clientCallName: 'client.sales.addresses.delete',
    fullyQualifiedName: 'sales.addresses.delete',
    httpMethod: 'delete',
    httpPath: '/v1/sales/addresses/{id}',
  },
  {
    clientCallName: 'client.sales.accountStatuses.list',
    fullyQualifiedName: 'sales.accountStatuses.list',
    httpMethod: 'get',
    httpPath: '/v1/sales/account-statuses',
  },
  {
    clientCallName: 'client.sales.accountStatuses.retrieve',
    fullyQualifiedName: 'sales.accountStatuses.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/sales/account-statuses/{id}',
  },
  {
    clientCallName: 'client.sales.accountUsers.salesTargets.list',
    fullyQualifiedName: 'sales.accountUsers.salesTargets.list',
    httpMethod: 'get',
    httpPath: '/v1/sales/account-users/{id}/sales-targets',
  },
  {
    clientCallName: 'client.sales.accountUsers.salesTargets.create',
    fullyQualifiedName: 'sales.accountUsers.salesTargets.create',
    httpMethod: 'post',
    httpPath: '/v1/sales/account-users/{id}/sales-targets',
  },
  {
    clientCallName: 'client.sales.accountUsers.salesTargets.update',
    fullyQualifiedName: 'sales.accountUsers.salesTargets.update',
    httpMethod: 'put',
    httpPath: '/v1/sales/account-users/{id}/sales-targets/{target_id}',
  },
  {
    clientCallName: 'client.sales.priorities.list',
    fullyQualifiedName: 'sales.priorities.list',
    httpMethod: 'get',
    httpPath: '/v1/sales/priorities',
  },
  {
    clientCallName: 'client.sales.priorities.retrieve',
    fullyQualifiedName: 'sales.priorities.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/sales/priorities/{id}',
  },
  {
    clientCallName: 'client.sales.customers.list',
    fullyQualifiedName: 'sales.customers.list',
    httpMethod: 'get',
    httpPath: '/v1/sales/customers',
  },
  {
    clientCallName: 'client.sales.customers.retrieve',
    fullyQualifiedName: 'sales.customers.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/sales/customers/{id}',
  },
  {
    clientCallName: 'client.sales.customers.create',
    fullyQualifiedName: 'sales.customers.create',
    httpMethod: 'post',
    httpPath: '/v1/sales/customers',
  },
  {
    clientCallName: 'client.sales.customers.update',
    fullyQualifiedName: 'sales.customers.update',
    httpMethod: 'patch',
    httpPath: '/v1/sales/customers/{id}',
  },
  {
    clientCallName: 'client.sales.customers.delete',
    fullyQualifiedName: 'sales.customers.delete',
    httpMethod: 'delete',
    httpPath: '/v1/sales/customers/{id}',
  },
  {
    clientCallName: 'client.sales.customers.retrieveLeadTime',
    fullyQualifiedName: 'sales.customers.retrieveLeadTime',
    httpMethod: 'get',
    httpPath: '/v1/sales/customers/{id}/lead-time',
  },
  {
    clientCallName: 'client.sales.customers.actions.merge',
    fullyQualifiedName: 'sales.customers.actions.merge',
    httpMethod: 'post',
    httpPath: '/v1/sales/customers/{id}/actions/merge',
  },
  {
    clientCallName: 'client.sales.contacts.actions.findByEmail',
    fullyQualifiedName: 'sales.contacts.actions.findByEmail',
    httpMethod: 'post',
    httpPath: '/v1/sales/contacts/actions/find-by-email',
  },
  {
    clientCallName: 'client.sales.orderDiscounts.list',
    fullyQualifiedName: 'sales.orderDiscounts.list',
    httpMethod: 'get',
    httpPath: '/v1/sales/order-discounts',
  },
  {
    clientCallName: 'client.sales.orderDiscounts.retrieve',
    fullyQualifiedName: 'sales.orderDiscounts.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/sales/order-discounts/{id}',
  },
  {
    clientCallName: 'client.sales.orderDiscounts.create',
    fullyQualifiedName: 'sales.orderDiscounts.create',
    httpMethod: 'post',
    httpPath: '/v1/sales/order-discounts',
  },
  {
    clientCallName: 'client.sales.orderDiscounts.update',
    fullyQualifiedName: 'sales.orderDiscounts.update',
    httpMethod: 'patch',
    httpPath: '/v1/sales/order-discounts/{id}',
  },
  {
    clientCallName: 'client.sales.orderDiscounts.delete',
    fullyQualifiedName: 'sales.orderDiscounts.delete',
    httpMethod: 'delete',
    httpPath: '/v1/sales/order-discounts/{id}',
  },
  {
    clientCallName: 'client.sales.orderDiscounts.actions.findByCode',
    fullyQualifiedName: 'sales.orderDiscounts.actions.findByCode',
    httpMethod: 'post',
    httpPath: '/v1/sales/order-discounts/actions/find-by-code',
  },
  {
    clientCallName: 'client.sales.salesOrders.retrieveStatuses',
    fullyQualifiedName: 'sales.salesOrders.retrieveStatuses',
    httpMethod: 'get',
    httpPath: '/v1/sales/sales-orders/statuses',
  },
  {
    clientCallName: 'client.sales.salesOrders.list',
    fullyQualifiedName: 'sales.salesOrders.list',
    httpMethod: 'get',
    httpPath: '/v1/sales/sales-orders',
  },
  {
    clientCallName: 'client.sales.salesOrders.retrieve',
    fullyQualifiedName: 'sales.salesOrders.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/sales/sales-orders/{id}',
  },
  {
    clientCallName: 'client.sales.salesOrders.create',
    fullyQualifiedName: 'sales.salesOrders.create',
    httpMethod: 'post',
    httpPath: '/v1/sales/sales-orders',
  },
  {
    clientCallName: 'client.sales.salesOrders.update',
    fullyQualifiedName: 'sales.salesOrders.update',
    httpMethod: 'patch',
    httpPath: '/v1/sales/sales-orders/{id}',
  },
  {
    clientCallName: 'client.sales.salesOrders.delete',
    fullyQualifiedName: 'sales.salesOrders.delete',
    httpMethod: 'delete',
    httpPath: '/v1/sales/sales-orders/{id}',
  },
  {
    clientCallName: 'client.sales.salesOrders.checkout',
    fullyQualifiedName: 'sales.salesOrders.checkout',
    httpMethod: 'post',
    httpPath: '/v1/sales/sales-orders/{id}/checkout',
  },
  {
    clientCallName: 'client.sales.salesOrders.priceQuote',
    fullyQualifiedName: 'sales.salesOrders.priceQuote',
    httpMethod: 'post',
    httpPath: '/v1/sales/sales-orders/price-quote',
  },
  {
    clientCallName: 'client.sales.salesOrders.actions.bulkDelete',
    fullyQualifiedName: 'sales.salesOrders.actions.bulkDelete',
    httpMethod: 'post',
    httpPath: '/v1/sales/sales-orders/actions/bulk-delete',
  },
  {
    clientCallName: 'client.sales.salesOrders.actions.issue',
    fullyQualifiedName: 'sales.salesOrders.actions.issue',
    httpMethod: 'put',
    httpPath: '/v1/sales/sales-orders/{id}/actions/issue',
  },
  {
    clientCallName: 'client.sales.salesOrders.actions.unissue',
    fullyQualifiedName: 'sales.salesOrders.actions.unissue',
    httpMethod: 'put',
    httpPath: '/v1/sales/sales-orders/{id}/actions/unissue',
  },
  {
    clientCallName: 'client.sales.salesOrders.actions.close',
    fullyQualifiedName: 'sales.salesOrders.actions.close',
    httpMethod: 'put',
    httpPath: '/v1/sales/sales-orders/{id}/actions/close',
  },
  {
    clientCallName: 'client.sales.salesOrders.actions.open',
    fullyQualifiedName: 'sales.salesOrders.actions.open',
    httpMethod: 'put',
    httpPath: '/v1/sales/sales-orders/{id}/actions/open',
  },
  {
    clientCallName: 'client.sales.salesOrders.actions.quoteFreight',
    fullyQualifiedName: 'sales.salesOrders.actions.quoteFreight',
    httpMethod: 'post',
    httpPath: '/v1/sales/sales-orders/{id}/actions/quote-freight',
  },
  {
    clientCallName: 'client.sales.salesOrders.actions.quoteCommitment',
    fullyQualifiedName: 'sales.salesOrders.actions.quoteCommitment',
    httpMethod: 'post',
    httpPath: '/v1/sales/sales-orders/actions/quote-commitment',
  },
  {
    clientCallName: 'client.sales.salesOrders.actions.createProductionRun',
    fullyQualifiedName: 'sales.salesOrders.actions.createProductionRun',
    httpMethod: 'post',
    httpPath: '/v1/sales/sales-orders/{id}/actions/create-production-run',
  },
  {
    clientCallName: 'client.sales.salesOrders.lines.create',
    fullyQualifiedName: 'sales.salesOrders.lines.create',
    httpMethod: 'post',
    httpPath: '/v1/sales/sales-orders/{id}/lines',
  },
  {
    clientCallName: 'client.sales.salesOrders.lines.update',
    fullyQualifiedName: 'sales.salesOrders.lines.update',
    httpMethod: 'patch',
    httpPath: '/v1/sales/sales-orders/{id}/lines/{line_id}',
  },
  {
    clientCallName: 'client.sales.salesOrders.lines.delete',
    fullyQualifiedName: 'sales.salesOrders.lines.delete',
    httpMethod: 'delete',
    httpPath: '/v1/sales/sales-orders/{id}/lines/{line_id}',
  },
  {
    clientCallName: 'client.sales.salesOrders.lines.actions.reorder',
    fullyQualifiedName: 'sales.salesOrders.lines.actions.reorder',
    httpMethod: 'post',
    httpPath: '/v1/sales/sales-orders/{id}/lines/actions/reorder',
  },
  {
    clientCallName: 'client.sales.volumeDiscounts.list',
    fullyQualifiedName: 'sales.volumeDiscounts.list',
    httpMethod: 'get',
    httpPath: '/v1/sales/volume-discounts',
  },
  {
    clientCallName: 'client.sales.volumeDiscounts.retrieve',
    fullyQualifiedName: 'sales.volumeDiscounts.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/sales/volume-discounts/{id}',
  },
  {
    clientCallName: 'client.sales.volumeDiscounts.create',
    fullyQualifiedName: 'sales.volumeDiscounts.create',
    httpMethod: 'post',
    httpPath: '/v1/sales/volume-discounts',
  },
  {
    clientCallName: 'client.sales.volumeDiscounts.update',
    fullyQualifiedName: 'sales.volumeDiscounts.update',
    httpMethod: 'patch',
    httpPath: '/v1/sales/volume-discounts/{id}',
  },
  {
    clientCallName: 'client.sales.volumeDiscounts.delete',
    fullyQualifiedName: 'sales.volumeDiscounts.delete',
    httpMethod: 'delete',
    httpPath: '/v1/sales/volume-discounts/{id}',
  },
  {
    clientCallName: 'client.finance.retrieveTransactionTypes',
    fullyQualifiedName: 'finance.retrieveTransactionTypes',
    httpMethod: 'get',
    httpPath: '/v1/finance/transaction-types',
  },
  {
    clientCallName: 'client.finance.retrieveTransactionMethods',
    fullyQualifiedName: 'finance.retrieveTransactionMethods',
    httpMethod: 'get',
    httpPath: '/v1/finance/transaction-methods',
  },
  {
    clientCallName: 'client.finance.retrieveAdjustmentTypes',
    fullyQualifiedName: 'finance.retrieveAdjustmentTypes',
    httpMethod: 'get',
    httpPath: '/v1/finance/adjustment-types',
  },
  {
    clientCallName: 'client.finance.paymentTerms.list',
    fullyQualifiedName: 'finance.paymentTerms.list',
    httpMethod: 'get',
    httpPath: '/v1/finance/payment-terms',
  },
  {
    clientCallName: 'client.finance.paymentTerms.retrieve',
    fullyQualifiedName: 'finance.paymentTerms.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/finance/payment-terms/{id}',
  },
  {
    clientCallName: 'client.finance.paymentTerms.create',
    fullyQualifiedName: 'finance.paymentTerms.create',
    httpMethod: 'post',
    httpPath: '/v1/finance/payment-terms',
  },
  {
    clientCallName: 'client.finance.paymentTerms.update',
    fullyQualifiedName: 'finance.paymentTerms.update',
    httpMethod: 'patch',
    httpPath: '/v1/finance/payment-terms/{id}',
  },
  {
    clientCallName: 'client.finance.paymentTerms.delete',
    fullyQualifiedName: 'finance.paymentTerms.delete',
    httpMethod: 'delete',
    httpPath: '/v1/finance/payment-terms/{id}',
  },
  {
    clientCallName: 'client.operations.retrieveMachineDowntimeReasons',
    fullyQualifiedName: 'operations.retrieveMachineDowntimeReasons',
    httpMethod: 'get',
    httpPath: '/v1/operations/machine-downtime-reasons',
  },
  {
    clientCallName: 'client.operations.retrieveMachineStatus',
    fullyQualifiedName: 'operations.retrieveMachineStatus',
    httpMethod: 'get',
    httpPath: '/v1/operations/machine-status',
  },
  {
    clientCallName: 'client.operations.retrieveDemandOverrideTypes',
    fullyQualifiedName: 'operations.retrieveDemandOverrideTypes',
    httpMethod: 'get',
    httpPath: '/v1/operations/demand-override-types',
  },
  {
    clientCallName: 'client.operations.retrieveScheduleDeviationTypes',
    fullyQualifiedName: 'operations.retrieveScheduleDeviationTypes',
    httpMethod: 'get',
    httpPath: '/v1/operations/schedule-deviation-types',
  },
  {
    clientCallName: 'client.operations.shippingTerms.list',
    fullyQualifiedName: 'operations.shippingTerms.list',
    httpMethod: 'get',
    httpPath: '/v1/operations/shipping-terms',
  },
  {
    clientCallName: 'client.operations.shippingTerms.retrieve',
    fullyQualifiedName: 'operations.shippingTerms.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/operations/shipping-terms/{id}',
  },
  {
    clientCallName: 'client.operations.shippingTerms.create',
    fullyQualifiedName: 'operations.shippingTerms.create',
    httpMethod: 'post',
    httpPath: '/v1/operations/shipping-terms',
  },
  {
    clientCallName: 'client.operations.shippingTerms.update',
    fullyQualifiedName: 'operations.shippingTerms.update',
    httpMethod: 'patch',
    httpPath: '/v1/operations/shipping-terms/{id}',
  },
  {
    clientCallName: 'client.operations.shippingTerms.delete',
    fullyQualifiedName: 'operations.shippingTerms.delete',
    httpMethod: 'delete',
    httpPath: '/v1/operations/shipping-terms/{id}',
  },
  {
    clientCallName: 'client.operations.carriers.list',
    fullyQualifiedName: 'operations.carriers.list',
    httpMethod: 'get',
    httpPath: '/v1/operations/carriers',
  },
  {
    clientCallName: 'client.operations.carriers.retrieve',
    fullyQualifiedName: 'operations.carriers.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/operations/carriers/{id}',
  },
  {
    clientCallName: 'client.operations.carriers.create',
    fullyQualifiedName: 'operations.carriers.create',
    httpMethod: 'post',
    httpPath: '/v1/operations/carriers',
  },
  {
    clientCallName: 'client.operations.carriers.update',
    fullyQualifiedName: 'operations.carriers.update',
    httpMethod: 'patch',
    httpPath: '/v1/operations/carriers/{id}',
  },
  {
    clientCallName: 'client.operations.carriers.delete',
    fullyQualifiedName: 'operations.carriers.delete',
    httpMethod: 'delete',
    httpPath: '/v1/operations/carriers/{id}',
  },
  {
    clientCallName: 'client.operations.carriers.serviceLevels.list',
    fullyQualifiedName: 'operations.carriers.serviceLevels.list',
    httpMethod: 'get',
    httpPath: '/v1/operations/carriers/{carrier_id}/service-levels',
  },
  {
    clientCallName: 'client.operations.carriers.serviceLevels.retrieve',
    fullyQualifiedName: 'operations.carriers.serviceLevels.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/operations/carriers/{carrier_id}/service-levels/{id}',
  },
  {
    clientCallName: 'client.operations.carriers.serviceLevels.create',
    fullyQualifiedName: 'operations.carriers.serviceLevels.create',
    httpMethod: 'post',
    httpPath: '/v1/operations/carriers/{carrier_id}/service-levels',
  },
  {
    clientCallName: 'client.operations.carriers.serviceLevels.update',
    fullyQualifiedName: 'operations.carriers.serviceLevels.update',
    httpMethod: 'patch',
    httpPath: '/v1/operations/carriers/{carrier_id}/service-levels/{id}',
  },
  {
    clientCallName: 'client.operations.carriers.serviceLevels.delete',
    fullyQualifiedName: 'operations.carriers.serviceLevels.delete',
    httpMethod: 'delete',
    httpPath: '/v1/operations/carriers/{carrier_id}/service-levels/{id}',
  },
  {
    clientCallName: 'client.operations.departments.list',
    fullyQualifiedName: 'operations.departments.list',
    httpMethod: 'get',
    httpPath: '/v1/operations/departments',
  },
  {
    clientCallName: 'client.operations.departments.retrieve',
    fullyQualifiedName: 'operations.departments.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/operations/departments/{id}',
  },
  {
    clientCallName: 'client.operations.departments.create',
    fullyQualifiedName: 'operations.departments.create',
    httpMethod: 'post',
    httpPath: '/v1/operations/departments',
  },
  {
    clientCallName: 'client.operations.departments.update',
    fullyQualifiedName: 'operations.departments.update',
    httpMethod: 'patch',
    httpPath: '/v1/operations/departments/{id}',
  },
  {
    clientCallName: 'client.operations.departments.delete',
    fullyQualifiedName: 'operations.departments.delete',
    httpMethod: 'delete',
    httpPath: '/v1/operations/departments/{id}',
  },
  {
    clientCallName: 'client.operations.inventoryChangeLogs.list',
    fullyQualifiedName: 'operations.inventoryChangeLogs.list',
    httpMethod: 'get',
    httpPath: '/v1/operations/inventory-change-logs',
  },
  {
    clientCallName: 'client.operations.inventoryChangeLogs.retrieve',
    fullyQualifiedName: 'operations.inventoryChangeLogs.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/operations/inventory-change-logs/{id}',
  },
  {
    clientCallName: 'client.operations.inventoryChangeLogs.actions.export',
    fullyQualifiedName: 'operations.inventoryChangeLogs.actions.export',
    httpMethod: 'get',
    httpPath: '/v1/operations/inventory-change-logs/actions/export',
  },
  {
    clientCallName: 'client.operations.inventoryChangeLogs.actions.startExport',
    fullyQualifiedName: 'operations.inventoryChangeLogs.actions.startExport',
    httpMethod: 'post',
    httpPath: '/v1/operations/inventory-change-logs/actions/export',
  },
  {
    clientCallName: 'client.operations.machines.list',
    fullyQualifiedName: 'operations.machines.list',
    httpMethod: 'get',
    httpPath: '/v1/operations/machines',
  },
  {
    clientCallName: 'client.operations.machines.retrieve',
    fullyQualifiedName: 'operations.machines.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/operations/machines/{id}',
  },
  {
    clientCallName: 'client.operations.machines.create',
    fullyQualifiedName: 'operations.machines.create',
    httpMethod: 'post',
    httpPath: '/v1/operations/machines',
  },
  {
    clientCallName: 'client.operations.machines.update',
    fullyQualifiedName: 'operations.machines.update',
    httpMethod: 'patch',
    httpPath: '/v1/operations/machines/{id}',
  },
  {
    clientCallName: 'client.operations.machines.delete',
    fullyQualifiedName: 'operations.machines.delete',
    httpMethod: 'delete',
    httpPath: '/v1/operations/machines/{id}',
  },
  {
    clientCallName: 'client.operations.machineDowntimeEvents.list',
    fullyQualifiedName: 'operations.machineDowntimeEvents.list',
    httpMethod: 'get',
    httpPath: '/v1/operations/machine-downtime-events',
  },
  {
    clientCallName: 'client.operations.machineDowntimeEvents.retrieve',
    fullyQualifiedName: 'operations.machineDowntimeEvents.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/operations/machine-downtime-events/{id}',
  },
  {
    clientCallName: 'client.operations.machineDowntimeEvents.create',
    fullyQualifiedName: 'operations.machineDowntimeEvents.create',
    httpMethod: 'post',
    httpPath: '/v1/operations/machine-downtime-events',
  },
  {
    clientCallName: 'client.operations.machineDowntimeEvents.update',
    fullyQualifiedName: 'operations.machineDowntimeEvents.update',
    httpMethod: 'patch',
    httpPath: '/v1/operations/machine-downtime-events/{id}',
  },
  {
    clientCallName: 'client.operations.machineDowntimeEvents.delete',
    fullyQualifiedName: 'operations.machineDowntimeEvents.delete',
    httpMethod: 'delete',
    httpPath: '/v1/operations/machine-downtime-events/{id}',
  },
  {
    clientCallName: 'client.operations.demandOverrides.list',
    fullyQualifiedName: 'operations.demandOverrides.list',
    httpMethod: 'get',
    httpPath: '/v1/operations/demand-overrides',
  },
  {
    clientCallName: 'client.operations.demandOverrides.retrieve',
    fullyQualifiedName: 'operations.demandOverrides.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/operations/demand-overrides/{id}',
  },
  {
    clientCallName: 'client.operations.demandOverrides.create',
    fullyQualifiedName: 'operations.demandOverrides.create',
    httpMethod: 'post',
    httpPath: '/v1/operations/demand-overrides',
  },
  {
    clientCallName: 'client.operations.demandOverrides.update',
    fullyQualifiedName: 'operations.demandOverrides.update',
    httpMethod: 'patch',
    httpPath: '/v1/operations/demand-overrides/{id}',
  },
  {
    clientCallName: 'client.operations.demandOverrides.delete',
    fullyQualifiedName: 'operations.demandOverrides.delete',
    httpMethod: 'delete',
    httpPath: '/v1/operations/demand-overrides/{id}',
  },
  {
    clientCallName: 'client.operations.productionSchedules.list',
    fullyQualifiedName: 'operations.productionSchedules.list',
    httpMethod: 'get',
    httpPath: '/v1/operations/production-schedules',
  },
  {
    clientCallName: 'client.operations.productionSchedules.create',
    fullyQualifiedName: 'operations.productionSchedules.create',
    httpMethod: 'post',
    httpPath: '/v1/operations/production-schedules',
  },
  {
    clientCallName: 'client.operations.productionSchedules.retrieveCurrent',
    fullyQualifiedName: 'operations.productionSchedules.retrieveCurrent',
    httpMethod: 'get',
    httpPath: '/v1/operations/production-schedules/current',
  },
  {
    clientCallName: 'client.operations.productionSchedules.retrieve',
    fullyQualifiedName: 'operations.productionSchedules.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/operations/production-schedules/{id}',
  },
  {
    clientCallName: 'client.operations.productionSchedules.retrieveItemPolicies',
    fullyQualifiedName: 'operations.productionSchedules.retrieveItemPolicies',
    httpMethod: 'get',
    httpPath: '/v1/operations/production-schedules/{id}/item-policies',
  },
  {
    clientCallName: 'client.operations.productionSchedules.retrieveFinishedPolicies',
    fullyQualifiedName: 'operations.productionSchedules.retrieveFinishedPolicies',
    httpMethod: 'get',
    httpPath: '/v1/operations/production-schedules/{id}/finished-policies',
  },
  {
    clientCallName: 'client.operations.productionSchedules.retrieveFinishingLines',
    fullyQualifiedName: 'operations.productionSchedules.retrieveFinishingLines',
    httpMethod: 'get',
    httpPath: '/v1/operations/production-schedules/{id}/finishing-lines',
  },
  {
    clientCallName: 'client.operations.productionSchedules.retrieveDerivedLines',
    fullyQualifiedName: 'operations.productionSchedules.retrieveDerivedLines',
    httpMethod: 'get',
    httpPath: '/v1/operations/production-schedules/{id}/derived-lines',
  },
  {
    clientCallName: 'client.operations.productionSchedules.retrieveAtRiskOrders',
    fullyQualifiedName: 'operations.productionSchedules.retrieveAtRiskOrders',
    httpMethod: 'get',
    httpPath: '/v1/operations/production-schedules/{id}/at-risk-orders',
  },
  {
    clientCallName: 'client.operations.productionSchedules.retrieveDeviations',
    fullyQualifiedName: 'operations.productionSchedules.retrieveDeviations',
    httpMethod: 'get',
    httpPath: '/v1/operations/production-schedules/{id}/deviations',
  },
  {
    clientCallName: 'client.operations.productionSchedules.retrieveWeekReleasePreview',
    fullyQualifiedName: 'operations.productionSchedules.retrieveWeekReleasePreview',
    httpMethod: 'get',
    httpPath: '/v1/operations/production-schedules/{id}/week-release-preview',
  },
  {
    clientCallName: 'client.operations.productionSchedules.delete',
    fullyQualifiedName: 'operations.productionSchedules.delete',
    httpMethod: 'delete',
    httpPath: '/v1/operations/production-schedules/{id}',
  },
  {
    clientCallName: 'client.operations.productionSchedules.lines.list',
    fullyQualifiedName: 'operations.productionSchedules.lines.list',
    httpMethod: 'get',
    httpPath: '/v1/operations/production-schedules/{id}/lines',
  },
  {
    clientCallName: 'client.operations.productionSchedules.lines.create',
    fullyQualifiedName: 'operations.productionSchedules.lines.create',
    httpMethod: 'post',
    httpPath: '/v1/operations/production-schedules/{id}/lines',
  },
  {
    clientCallName: 'client.operations.productionSchedules.lines.update',
    fullyQualifiedName: 'operations.productionSchedules.lines.update',
    httpMethod: 'patch',
    httpPath: '/v1/operations/production-schedules/{id}/lines/{line_id}',
  },
  {
    clientCallName: 'client.operations.productionSchedules.lines.delete',
    fullyQualifiedName: 'operations.productionSchedules.lines.delete',
    httpMethod: 'delete',
    httpPath: '/v1/operations/production-schedules/{id}/lines/{line_id}',
  },
  {
    clientCallName: 'client.operations.productionSchedules.actions.preview',
    fullyQualifiedName: 'operations.productionSchedules.actions.preview',
    httpMethod: 'put',
    httpPath: '/v1/operations/production-schedules/actions/preview',
  },
  {
    clientCallName: 'client.operations.productionSchedules.actions.previewRegenerate',
    fullyQualifiedName: 'operations.productionSchedules.actions.previewRegenerate',
    httpMethod: 'put',
    httpPath: '/v1/operations/production-schedules/{id}/actions/preview-regenerate',
  },
  {
    clientCallName: 'client.operations.productionSchedules.actions.regenerate',
    fullyQualifiedName: 'operations.productionSchedules.actions.regenerate',
    httpMethod: 'put',
    httpPath: '/v1/operations/production-schedules/{id}/actions/regenerate',
  },
  {
    clientCallName: 'client.operations.productionSchedules.actions.publish',
    fullyQualifiedName: 'operations.productionSchedules.actions.publish',
    httpMethod: 'put',
    httpPath: '/v1/operations/production-schedules/{id}/actions/publish',
  },
  {
    clientCallName: 'client.operations.productionSchedules.actions.releaseWeek',
    fullyQualifiedName: 'operations.productionSchedules.actions.releaseWeek',
    httpMethod: 'post',
    httpPath: '/v1/operations/production-schedules/{id}/actions/release-week',
  },
  {
    clientCallName: 'client.operations.productionSchedules.actions.archive',
    fullyQualifiedName: 'operations.productionSchedules.actions.archive',
    httpMethod: 'put',
    httpPath: '/v1/operations/production-schedules/{id}/actions/archive',
  },
  {
    clientCallName: 'client.operations.productionScheduleSettings.list',
    fullyQualifiedName: 'operations.productionScheduleSettings.list',
    httpMethod: 'get',
    httpPath: '/v1/operations/production-schedule-settings',
  },
  {
    clientCallName: 'client.operations.productionScheduleSettings.update',
    fullyQualifiedName: 'operations.productionScheduleSettings.update',
    httpMethod: 'put',
    httpPath: '/v1/operations/production-schedule-settings',
  },
  {
    clientCallName: 'client.operations.productionScheduleSettings.resources.list',
    fullyQualifiedName: 'operations.productionScheduleSettings.resources.list',
    httpMethod: 'get',
    httpPath: '/v1/operations/production-schedule-settings/resources',
  },
  {
    clientCallName: 'client.operations.productionScheduleSettings.resources.update',
    fullyQualifiedName: 'operations.productionScheduleSettings.resources.update',
    httpMethod: 'put',
    httpPath: '/v1/operations/production-schedule-settings/resources',
  },
  {
    clientCallName: 'client.operations.productionScheduleSettings.resources.delete',
    fullyQualifiedName: 'operations.productionScheduleSettings.resources.delete',
    httpMethod: 'delete',
    httpPath: '/v1/operations/production-schedule-settings/resources/{id}',
  },
  {
    clientCallName: 'client.operations.productionScheduleSettings.items.list',
    fullyQualifiedName: 'operations.productionScheduleSettings.items.list',
    httpMethod: 'get',
    httpPath: '/v1/operations/production-schedule-settings/items',
  },
  {
    clientCallName: 'client.operations.productionScheduleSettings.items.retrieve',
    fullyQualifiedName: 'operations.productionScheduleSettings.items.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/operations/production-schedule-settings/items/{item_id}',
  },
  {
    clientCallName: 'client.operations.productionScheduleSettings.items.update',
    fullyQualifiedName: 'operations.productionScheduleSettings.items.update',
    httpMethod: 'put',
    httpPath: '/v1/operations/production-schedule-settings/items/{item_id}',
  },
  {
    clientCallName: 'client.operations.productionScheduleSettings.items.delete',
    fullyQualifiedName: 'operations.productionScheduleSettings.items.delete',
    httpMethod: 'delete',
    httpPath: '/v1/operations/production-schedule-settings/items/{item_id}',
  },
  {
    clientCallName: 'client.operations.fulfillmentRecommendations.list',
    fullyQualifiedName: 'operations.fulfillmentRecommendations.list',
    httpMethod: 'get',
    httpPath: '/v1/operations/fulfillment-recommendations',
  },
  {
    clientCallName: 'client.operations.fulfillmentRecommendations.actions.apply',
    fullyQualifiedName: 'operations.fulfillmentRecommendations.actions.apply',
    httpMethod: 'post',
    httpPath: '/v1/operations/fulfillment-recommendations/actions/apply',
  },
  {
    clientCallName: 'client.operations.operatingCalendars.list',
    fullyQualifiedName: 'operations.operatingCalendars.list',
    httpMethod: 'get',
    httpPath: '/v1/operations/operating-calendars',
  },
  {
    clientCallName: 'client.operations.operatingCalendars.retrieve',
    fullyQualifiedName: 'operations.operatingCalendars.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/operations/operating-calendars/{id}',
  },
  {
    clientCallName: 'client.operations.operatingCalendars.create',
    fullyQualifiedName: 'operations.operatingCalendars.create',
    httpMethod: 'post',
    httpPath: '/v1/operations/operating-calendars',
  },
  {
    clientCallName: 'client.operations.operatingCalendars.update',
    fullyQualifiedName: 'operations.operatingCalendars.update',
    httpMethod: 'patch',
    httpPath: '/v1/operations/operating-calendars/{id}',
  },
  {
    clientCallName: 'client.operations.operatingCalendars.delete',
    fullyQualifiedName: 'operations.operatingCalendars.delete',
    httpMethod: 'delete',
    httpPath: '/v1/operations/operating-calendars/{id}',
  },
  {
    clientCallName: 'client.operations.operatingCalendars.closures.list',
    fullyQualifiedName: 'operations.operatingCalendars.closures.list',
    httpMethod: 'get',
    httpPath: '/v1/operations/operating-calendars/{id}/closures',
  },
  {
    clientCallName: 'client.operations.operatingCalendars.closures.create',
    fullyQualifiedName: 'operations.operatingCalendars.closures.create',
    httpMethod: 'post',
    httpPath: '/v1/operations/operating-calendars/{id}/closures',
  },
  {
    clientCallName: 'client.operations.operatingCalendars.closures.delete',
    fullyQualifiedName: 'operations.operatingCalendars.closures.delete',
    httpMethod: 'delete',
    httpPath: '/v1/operations/operating-calendars/{id}/closures/{closure_id}',
  },
  {
    clientCallName: 'client.operations.picks.list',
    fullyQualifiedName: 'operations.picks.list',
    httpMethod: 'get',
    httpPath: '/v1/operations/picks',
  },
  {
    clientCallName: 'client.operations.picks.retrieve',
    fullyQualifiedName: 'operations.picks.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/operations/picks/{id}',
  },
  {
    clientCallName: 'client.operations.picks.actions.pick',
    fullyQualifiedName: 'operations.picks.actions.pick',
    httpMethod: 'put',
    httpPath: '/v1/operations/picks/{id}/actions/pick',
  },
  {
    clientCallName: 'client.operations.picks.actions.void',
    fullyQualifiedName: 'operations.picks.actions.void',
    httpMethod: 'put',
    httpPath: '/v1/operations/picks/{id}/actions/void',
  },
  {
    clientCallName: 'client.operations.picks.actions.pack',
    fullyQualifiedName: 'operations.picks.actions.pack',
    httpMethod: 'post',
    httpPath: '/v1/operations/picks/{id}/actions/pack',
  },
  {
    clientCallName: 'client.operations.picks.lines.update',
    fullyQualifiedName: 'operations.picks.lines.update',
    httpMethod: 'patch',
    httpPath: '/v1/operations/picks/{pick_id}/lines/{id}',
  },
  {
    clientCallName: 'client.operations.picks.lines.actions.pick',
    fullyQualifiedName: 'operations.picks.lines.actions.pick',
    httpMethod: 'put',
    httpPath: '/v1/operations/picks/{pick_id}/lines/{id}/actions/pick',
  },
  {
    clientCallName: 'client.operations.picks.lines.actions.void',
    fullyQualifiedName: 'operations.picks.lines.actions.void',
    httpMethod: 'put',
    httpPath: '/v1/operations/picks/{pick_id}/lines/{id}/actions/void',
  },
  {
    clientCallName: 'client.operations.locations.list',
    fullyQualifiedName: 'operations.locations.list',
    httpMethod: 'get',
    httpPath: '/v1/operations/locations',
  },
  {
    clientCallName: 'client.operations.locations.retrieve',
    fullyQualifiedName: 'operations.locations.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/operations/locations/{id}',
  },
  {
    clientCallName: 'client.operations.locations.create',
    fullyQualifiedName: 'operations.locations.create',
    httpMethod: 'post',
    httpPath: '/v1/operations/locations',
  },
  {
    clientCallName: 'client.operations.locations.update',
    fullyQualifiedName: 'operations.locations.update',
    httpMethod: 'patch',
    httpPath: '/v1/operations/locations/{id}',
  },
  {
    clientCallName: 'client.operations.locations.delete',
    fullyQualifiedName: 'operations.locations.delete',
    httpMethod: 'delete',
    httpPath: '/v1/operations/locations/{id}',
  },
  {
    clientCallName: 'client.operations.locations.actions.bulkUpsert',
    fullyQualifiedName: 'operations.locations.actions.bulkUpsert',
    httpMethod: 'post',
    httpPath: '/v1/operations/locations/actions/bulk-upsert',
  },
  {
    clientCallName: 'client.operations.locationTypes.list',
    fullyQualifiedName: 'operations.locationTypes.list',
    httpMethod: 'get',
    httpPath: '/v1/operations/location-types',
  },
  {
    clientCallName: 'client.operations.locationTypes.retrieve',
    fullyQualifiedName: 'operations.locationTypes.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/operations/location-types/{id}',
  },
  {
    clientCallName: 'client.operations.shipments.actions.rateShop',
    fullyQualifiedName: 'operations.shipments.actions.rateShop',
    httpMethod: 'post',
    httpPath: '/v1/operations/shipments/actions/rate-shop',
  },
  {
    clientCallName: 'client.operations.scanningStations.list',
    fullyQualifiedName: 'operations.scanningStations.list',
    httpMethod: 'get',
    httpPath: '/v1/operations/scanning-stations',
  },
  {
    clientCallName: 'client.operations.scanningStations.retrieve',
    fullyQualifiedName: 'operations.scanningStations.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/operations/scanning-stations/{id}',
  },
  {
    clientCallName: 'client.operations.scanningStations.create',
    fullyQualifiedName: 'operations.scanningStations.create',
    httpMethod: 'post',
    httpPath: '/v1/operations/scanning-stations',
  },
  {
    clientCallName: 'client.operations.scanningStations.update',
    fullyQualifiedName: 'operations.scanningStations.update',
    httpMethod: 'patch',
    httpPath: '/v1/operations/scanning-stations/{id}',
  },
  {
    clientCallName: 'client.operations.scanningStations.delete',
    fullyQualifiedName: 'operations.scanningStations.delete',
    httpMethod: 'delete',
    httpPath: '/v1/operations/scanning-stations/{id}',
  },
  {
    clientCallName: 'client.identity.retrievePermissionGroups',
    fullyQualifiedName: 'identity.retrievePermissionGroups',
    httpMethod: 'get',
    httpPath: '/v1/identity/permission-groups',
  },
  {
    clientCallName: 'client.identity.accountUsers.list',
    fullyQualifiedName: 'identity.accountUsers.list',
    httpMethod: 'get',
    httpPath: '/v1/identity/account-users',
  },
  {
    clientCallName: 'client.identity.accountUsers.retrieve',
    fullyQualifiedName: 'identity.accountUsers.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/identity/account-users/{id}',
  },
  {
    clientCallName: 'client.identity.accountUsers.create',
    fullyQualifiedName: 'identity.accountUsers.create',
    httpMethod: 'post',
    httpPath: '/v1/identity/account-users',
  },
  {
    clientCallName: 'client.identity.accountUsers.update',
    fullyQualifiedName: 'identity.accountUsers.update',
    httpMethod: 'patch',
    httpPath: '/v1/identity/account-users/{id}',
  },
  {
    clientCallName: 'client.identity.accountUsers.actions.activate',
    fullyQualifiedName: 'identity.accountUsers.actions.activate',
    httpMethod: 'put',
    httpPath: '/v1/identity/account-users/{id}/actions/activate',
  },
  {
    clientCallName: 'client.identity.accountUsers.actions.disable',
    fullyQualifiedName: 'identity.accountUsers.actions.disable',
    httpMethod: 'put',
    httpPath: '/v1/identity/account-users/{id}/actions/disable',
  },
  {
    clientCallName: 'client.identity.accountUsers.actions.remove',
    fullyQualifiedName: 'identity.accountUsers.actions.remove',
    httpMethod: 'put',
    httpPath: '/v1/identity/account-users/{id}/actions/remove',
  },
  {
    clientCallName: 'client.identity.accounts.updateFavicon',
    fullyQualifiedName: 'identity.accounts.updateFavicon',
    httpMethod: 'put',
    httpPath: '/v1/identity/accounts/{id}/favicon',
  },
  {
    clientCallName: 'client.identity.roles.list',
    fullyQualifiedName: 'identity.roles.list',
    httpMethod: 'get',
    httpPath: '/v1/identity/roles',
  },
  {
    clientCallName: 'client.identity.roles.retrieve',
    fullyQualifiedName: 'identity.roles.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/identity/roles/{id}',
  },
  {
    clientCallName: 'client.identity.roles.create',
    fullyQualifiedName: 'identity.roles.create',
    httpMethod: 'post',
    httpPath: '/v1/identity/roles',
  },
  {
    clientCallName: 'client.identity.roles.update',
    fullyQualifiedName: 'identity.roles.update',
    httpMethod: 'patch',
    httpPath: '/v1/identity/roles/{id}',
  },
  {
    clientCallName: 'client.identity.roles.delete',
    fullyQualifiedName: 'identity.roles.delete',
    httpMethod: 'delete',
    httpPath: '/v1/identity/roles/{id}',
  },
  {
    clientCallName: 'client.settings.portalDomains.create',
    fullyQualifiedName: 'settings.portalDomains.create',
    httpMethod: 'post',
    httpPath: '/v1/settings/portal-domains',
  },
  {
    clientCallName: 'client.settings.portalDomains.list',
    fullyQualifiedName: 'settings.portalDomains.list',
    httpMethod: 'get',
    httpPath: '/v1/settings/portal-domains',
  },
  {
    clientCallName: 'client.settings.portalDomains.retrieve',
    fullyQualifiedName: 'settings.portalDomains.retrieve',
    httpMethod: 'get',
    httpPath: '/v1/settings/portal-domains/{id}',
  },
  {
    clientCallName: 'client.settings.portalDomains.delete',
    fullyQualifiedName: 'settings.portalDomains.delete',
    httpMethod: 'delete',
    httpPath: '/v1/settings/portal-domains/{id}',
  },
  {
    clientCallName: 'client.settings.portalDomains.actions.verify',
    fullyQualifiedName: 'settings.portalDomains.actions.verify',
    httpMethod: 'post',
    httpPath: '/v1/settings/portal-domains/{id}/actions/verify',
  },
  {
    clientCallName: 'client.settings.integrations.list',
    fullyQualifiedName: 'settings.integrations.list',
    httpMethod: 'get',
    httpPath: '/v1/settings/integrations',
  },
  {
    clientCallName: 'client.settings.integrations.create',
    fullyQualifiedName: 'settings.integrations.create',
    httpMethod: 'post',
    httpPath: '/v1/settings/integrations',
  },
  {
    clientCallName: 'client.settings.integrations.update',
    fullyQualifiedName: 'settings.integrations.update',
    httpMethod: 'put',
    httpPath: '/v1/settings/integrations/{id}',
  },
  {
    clientCallName: 'client.settings.integrations.delete',
    fullyQualifiedName: 'settings.integrations.delete',
    httpMethod: 'delete',
    httpPath: '/v1/settings/integrations/{id}',
  },
];

function allowedMethodsForCodeTool(options: McpOptions | undefined): SdkMethod[] | undefined {
  if (!options) {
    return undefined;
  }

  let allowedMethods: SdkMethod[];

  if (options.codeAllowHttpGets || options.codeAllowedMethods) {
    // Start with nothing allowed and then add into it from options
    let allowedMethodsSet = new Set<SdkMethod>();

    if (options.codeAllowHttpGets) {
      // Add all methods that map to an HTTP GET
      sdkMethods
        .filter((method) => method.httpMethod === 'get')
        .forEach((method) => allowedMethodsSet.add(method));
    }

    if (options.codeAllowedMethods) {
      // Add all methods that match any of the allowed regexps
      const allowedRegexps = options.codeAllowedMethods.map((pattern) => {
        try {
          return new RegExp(pattern);
        } catch (e) {
          throw new Error(
            `Invalid regex pattern for allowed method: "${pattern}": ${e instanceof Error ? e.message : e}`,
          );
        }
      });

      sdkMethods
        .filter((method) => allowedRegexps.some((regexp) => regexp.test(method.fullyQualifiedName)))
        .forEach((method) => allowedMethodsSet.add(method));
    }

    allowedMethods = Array.from(allowedMethodsSet);
  } else {
    // Start with everything allowed
    allowedMethods = [...sdkMethods];
  }

  if (options.codeBlockedMethods) {
    // Filter down based on blocked regexps
    const blockedRegexps = options.codeBlockedMethods.map((pattern) => {
      try {
        return new RegExp(pattern);
      } catch (e) {
        throw new Error(
          `Invalid regex pattern for blocked method: "${pattern}": ${e instanceof Error ? e.message : e}`,
        );
      }
    });

    allowedMethods = allowedMethods.filter(
      (method) => !blockedRegexps.some((regexp) => regexp.test(method.fullyQualifiedName)),
    );
  }

  return allowedMethods;
}

export function blockedMethodsForCodeTool(options: McpOptions | undefined): SdkMethod[] | undefined {
  const allowedMethods = allowedMethodsForCodeTool(options);
  if (!allowedMethods) {
    return undefined;
  }

  const allowedSet = new Set(allowedMethods.map((method) => method.fullyQualifiedName));

  // Return any methods that are not explicitly allowed
  return sdkMethods.filter((method) => !allowedSet.has(method.fullyQualifiedName));
}
